---
- name: Discover the AWX and PostgreSQL nodes
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Write kubeconfig to a temporary file
      ansible.builtin.copy:
        content: "{{ kubeconfig_content }}"
        dest: /tmp/kubeconfig
        mode: '0600'
      delegate_to: localhost

    - name: Get AWX web pod info to find its node
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: awx
        kubeconfig: /tmp/kubeconfig
        label_selectors:
          - "app.kubernetes.io/component=awx-web"
      register: awx_pod_info

    - name: Get PostgreSQL pod info to find its node
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: awx
        kubeconfig: /tmp/kubeconfig
        label_selectors:
          - "app.kubernetes.io/component=awx-postgres"
      register: postgres_pod_info

    - name: Set facts for the AWX and Postgres node names
      ansible.builtin.set_fact:
        awx_node_name: "{{ awx_pod_info.resources[0].spec.nodeName }}"
        postgres_node_name: "{{ postgres_pod_info.resources[0].spec.nodeName }}"

- name: Patch and reboot all non-AWX nodes
  hosts: "RP5N:!{{ awx_node_name }}:!{{ postgres_node_name }}"
  become: true
  serial: 1

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      
    - name: Perform a full system upgrade
      ansible.builtin.apt:
        upgrade: full
        autoremove: yes
      register: upgrade_result
      
    - name: Reboot if required
      ansible.builtin.reboot:
      when: upgrade_result.changed
      
    - name: Wait for system to come back online
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300
      when: upgrade_result.changed

- name: Report which nodes were not patched
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display the names of the skipped nodes
      ansible.builtin.debug:
        msg: "The nodes {{ awx_node_name }} and {{ postgres_node_name }} were not patched because they are running AWX components."
